# Generated by Django 4.2.6 on 2023-10-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('id_usuario', models.IntegerField(default=0)),
                ('codigo_qr', models.ImageField(blank=True, editable=False, null=True, upload_to='gymapp')),
            ],
        ),
    ]
