# Generated by Django 4.2.6 on 2023-10-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_rename_usuario_usuario_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes_gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plan', models.CharField(choices=[('M', 'Mensual'), ('S', 'Semanal'), ('O', 'Personalizado')], max_length=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='usuario_gym',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.planes_gym'),
        ),
    ]
