# Generated by Django 4.2.6 on 2023-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_planes_gym_usuario_gym_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_gym',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
