# Generated by Django 4.2.6 on 2023-10-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_alter_planes_gym_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_gym',
            name='tipo_id',
            field=models.CharField(choices=[('cedula de ciudadania', 'Cédula de Ciudadanía'), ('tarjeta de identidad', 'Tarjeta de Identidad'), ('cedula de extranjeria', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('permiso especial permanencia', 'Permiso Especial de Permanencia')], default='cedula de ciudadania', max_length=50),
        ),
        migrations.AlterField(
            model_name='planes_gym',
            name='tipo_plan',
            field=models.CharField(choices=[('A', 'Anual'), ('M', 'Mensual'), ('S', 'Semanal'), ('D', 'Diario'), ('O', 'Personalizado')], max_length=1),
        ),
    ]
