# Generated by Django 4.2.6 on 2023-10-15 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_usuario_gym_tipo_id_alter_planes_gym_tipo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
