# Generated by Django 4.2.6 on 2023-10-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_usuario_gym_fecha_fin_usuario_gym_fecha_inicio_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_gym',
            name='tipo_plan',
            field=models.CharField(choices=[('A', 'Anual'), ('M', 'Mensual'), ('S3', '21 Días'), ('S2', '15 Días'), ('S', 'Semanal'), ('D', 'Diario'), ('O', 'Personalizado')], max_length=2),
        ),
    ]
