# Generated by Django 4.2.6 on 2023-10-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_asistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
