# Generated by Django 4.2.6 on 2023-10-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_rename_usuario_asistencia_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
