# Generated by Django 4.2.6 on 2023-10-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_rename_usuario_id_asistencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=True),
        ),
    ]
