# Generated by Django 4.2.6 on 2023-11-02 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_alter_asistencia_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 19, 59, 52, 367158)),
        ),
    ]
