# Generated by Django 4.2.6 on 2023-11-02 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_alter_usuario_gym_fecha_inicio_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 20, 0, 32, 270567)),
        ),
    ]
