# Generated by Django 4.2.6 on 2023-11-04 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_alter_usuario_gym_fecha_inicio_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_gym',
            name='tipo_plan',
            field=models.CharField(choices=[('A', 'Anual'), ('T', 'Trimestral'), ('M', 'Mensual'), ('S3', '21 Días'), ('S2', '15 Días'), ('S', 'Semanal'), ('D', 'Diario'), ('O', 'Personalizado')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 17, 13, 3, 156677)),
        ),
    ]
