# Generated by Django 4.2.6 on 2023-11-04 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_alter_planes_gym_tipo_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 18, 1, 12, 618424)),
        ),
    ]
