# Generated by Django 4.2.6 on 2023-11-20 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0018_alter_usuario_gym_fecha_inicio_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes_gym',
            name='dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2024, 11, 19)),
        ),
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
