# Generated by Django 4.2.6 on 2023-11-20 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0019_planes_gym_dias_alter_usuario_gym_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
