# Generated by Django 4.2.6 on 2023-11-21 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0021_alter_usuario_gym_fecha_inicio_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_gym',
            name='tipo_plan',
            field=models.CharField(choices=[('Anual', 'Anual'), ('Trimestral', 'Trimestral'), ('Mensual', 'Mensual'), ('Semanal x3', '21 Días'), ('Semanal x2', '15 Días'), ('Semanal', 'Semanal'), ('Diario', 'Diario'), ('Personalizado', 'Personalizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2024, 11, 20)),
        ),
    ]
