# Generated by Django 4.2.6 on 2023-11-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0022_alter_planes_gym_tipo_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes_gym',
            name='tipo_plan',
            field=models.CharField(choices=[('A', 'Anual'), ('T', 'Trimestral'), ('M', 'Mensual'), ('S3', '21 Días'), ('S2', '15 Días'), ('S', 'Semanal'), ('D', 'Diario'), ('P', 'Personalizado')], max_length=20),
        ),
    ]
