# Generated by Django 4.2.6 on 2023-11-22 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0023_alter_planes_gym_tipo_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2024, 11, 21)),
        ),
    ]
