# Generated by Django 4.2.6 on 2023-11-25 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0025_alter_usuario_gym_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2024, 11, 24)),
        ),
    ]
