# Generated by Django 4.2.6 on 2023-11-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0027_alter_usuario_gym_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='tipo_id',
            field=models.CharField(choices=[('cedula', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('ce', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('pep', 'Permiso Especial de Permanencia')], max_length=50),
        ),
    ]
