# Generated by Django 4.2.6 on 2023-11-30 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0030_registroganancia_gasto_diario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2024, 11, 29)),
        ),
    ]
