# Generated by Django 4.2.6 on 2023-11-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0031_alter_usuario_gym_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plan', models.CharField(max_length=20, unique=True)),
                ('precio', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
            ],
        ),
    ]
