# Generated by Django 4.2.6 on 2023-12-01 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0032_plandinamico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2024, 11, 30)),
        ),
    ]
