# Generated by Django 4.2.6 on 2023-12-02 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0033_alter_usuario_gym_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2024, 12, 1)),
        ),
    ]
