# Generated by Django 4.2.6 on 2024-01-25 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0034_alter_usuario_gym_fecha_fin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanDinamico',
        ),
        migrations.AlterField(
            model_name='planes_gym',
            name='tipo_plan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_gym',
            name='fecha_inicio_gym',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario_gym',
            name='tipo_id',
            field=models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Permiso Especial de Permanencia', 'Permiso Especial de Permanencia')], max_length=50),
        ),
    ]
