# Generated by Django 4.2.6 on 2024-03-02 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0035_delete_plandinamico_alter_planes_gym_tipo_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 50, 37, 364380)),
        ),
    ]
